//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PdfContent { get; set; }
        public string UploaderName { get; set; }
        public int UploaderId { get; set; }
        public int AdminId { get; set; }
        public int VerifierId { get; set; }
    
        public virtual Uploader Uploader { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Verifier Verifier { get; set; }
    }
}
